version: "3.2"

services:
  nginx:
    restart: "always"
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: .
        target: /code
    deploy:
      resources:
        limits:
          memory: 100m